### ISSUE TITLE
.vimrc + Rust

### ISSUE THREAD

**Issue by ahirner** [Schr3da/godot-rust#2]
Rather unrelated, but your setup looks well put together! Would you mind sharing it at some point?

**Comment by Schr3da** [comment]
Sure happy to share it... Thats my current setup. hope you dont mind that it is not limited to rust :) 

https://gist.github.com/Schr3da/2fe30a7467ff6e8ca179f455d3fa4494

I basically use coc for nvim. and with that i install all the required plugins like coc-rls. 
Please ensure that you have rust already installed otherwise you might face some issues... 

as addon manager i use vimplug ... 
https://github.com/junegunn/vim-plug

let me know if you need any help!

regards
schr3da

**Comment by ahirner** [comment]
Your init looks very lean still, hence perfect to borrow from and finally pitch against intellij+ideavim. Thx a lot!
